<a href="https://colab.research.google.com/github/PedroConst/EQE-400-Modelagem/blob/main/Python/Aula_2_Variaveis_Funcoes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 02: Variáveis e Funções



Até o momento, estamos utilizando o Python apenas como uma calculadora científica para avaliar expressões aritméticas. <br> Nesta aula vamos aprender a definir diferentes tipos de variáveis e funções em Python. Isso nos permitirá ter liberdade para trabalhar com expressões algébricas.

## 1. Variáveis

Uma **variável** é um recipiente que armazena uma informação na memória do computador. <br>
O nome da variável diz ao computador onde encontrar esse valor na memória.  

---
**Exemplo:** Armazenar o valor 2 na variável x.


---


In [ ]:
x = 2
x



---
**Exemplo:** Armazenar o valor 5 na variável y, multiplicar por 4 e observar resultado.


---




In [ ]:
y = 5
y*4

Os nomes das variáveis devem seguir as seguintes regras:


*   Somente caracteres alfa-numéricos (letras e números) e *underscore* (_);
*   Primeiro caractere deve ser uma letra ou underscore;
*   Espaços não são permitidos;
*   Sensível a maiúsculas e minúsculas.

Exemplos:


*   Permitidos: `distAB`, `raio2`, `dens_rho`, `camelCase`
*   Proibidos: `2raio`, `número de carros`, `dens!`







---
**Exemplo:** Listar todas as variáveis armazenadas neste Notebook com um comando mágico (*magic command*).

---



In [ ]:
%whos

***Atenção!*** Em programação, a expressão $x=y$ **não** significa igualdade matemática. <br>
Apenas significa que o valor da direita está sendo armazenado na **esquerda** (i.e., $x←y$)




In [ ]:
x = x + 1
x

In [ ]:
x = 1
y = x + 1
x = 2
y

---
**Exemplo:** Limpar algumas variáveis armazenadas neste Notebook com um comando mágico (*magic command*).

---

In [ ]:
del y

In [ ]:
%whos

---
**Exemplo:** Limpar todas as variáveis armazenadas neste Notebook com um comando mágico (*magic command*).

---

In [ ]:
%reset

##2. Estrutura de Dados

### 2.1 String `"Texto"`

Uma `string` é uma sequência de caracteres. Para definir uma variável como `string` basta utilizar aspas `'simples'` ou `"duplas"`.



---
**Exemplo:** Imprima "Eu amo Python!" na tela usando a função `print`.


---




In [ ]:
print("Eu amo Python!")



---
**Exemplo:** Armazene essa `string` em uma variável `w`.


---




In [ ]:
w = "Eu amo Python!"
print(w)
type(w)



---
**Exemplo:** Determine o comprimento desta variável `w` usando `len()`.


---




In [ ]:
len(w)



---
**Exemplo:** Recupere pedaços da variável `w` usando fatiamento (*slicing*) como `[início:fim:passo]`


---

Regras para *slicing*:


*   O índice da posição começa em `0` (zero);
*   O limite superior é excludente (ex.: `[6:11]` inclui os índices `6` a `10`);
*   O passo padrão é `1` quando o passo não é especificado;
*   Índices negativos podem ser usados para contar de trás pra frente (ex.: -1 é o último caractere, -2 o penúltimo, etc.)





In [ ]:
w[7]

In [ ]:
w[3:6]

In [ ]:
w[7:]

In [ ]:
w[:2]

In [ ]:
w[10:-1]

In [ ]:
w[::4]



---
**Exemplo:** Concatenar duas variáveis do tipo `string`.


---




In [ ]:
str_a = "Eu amo Python! "
str_b = "Você também!"
print(str_a + str_b)



---
**Exemplo:** Imprimir `x = 1` na tela.


---




In [ ]:
x = 1
print("x = " + x)

In [ ]:
print("x = " + str(x))

###2.2 Listas `[a,b,c]`

Uma lista é definida por colchetes `[ ]` e consegue armazenar quaisquer tipos de dados (números, strings, outros). <br>
Cada elemento da lista é separado por uma vírgula.


---
**Exemplo:** Criar uma lista de números, outra lista de strings e concatenar ambas.


---




In [ ]:
lista_1 = [1,2,3]
lista_1

In [ ]:
lista_2 = ["Métodos", "Numéricos"]
lista_2

In [ ]:
lista_3 = lista_1 + lista_2
lista_3



---
**Exemplo:** Fazer fatiamento da `lista_3`.


---




In [ ]:
lista_3[2]

In [ ]:
lista_3[:3]

In [ ]:
lista_3[-1]

In [ ]:
lista_3[0]



---
**Exemplo:** Adicionar/Remover elementos da `lista_3`.


---




In [ ]:
lista_3.append("Python")
lista_3

In [ ]:
lista_3.remove("Python")
lista_3

In [ ]:
lista_3.insert(3,"Python")
lista_3

In [ ]:
del lista_3[3]
lista_3

### 2.3 Tuples `(a,b,c)`

Um tuple é definido por parênteses `( )` com elementos separados por vírgulas. Portanto, é semelhante às listas. Porém, os elementos de um tuple são **imutáveis**, enquanto os elementos das listas podem ser alterados.



---
**Exemplo:** Definir um tuple e tentar modificar seus elementos.


---




In [ ]:
tuple_1 = (1,2,3,4)
tuple_1

In [ ]:
tuple_1[2]=1

In [ ]:
lista_1[2]=1
lista_1



---
**Exemplo:** Fatiar e determinar o comprimento de tuples.


---




In [ ]:
tuple_1[1:3]

In [ ]:
len(tuple_1)

### 2.4 Conjuntos (*Sets*) `{a,b,c}`

Conjuntos são coleções desordenadas sem duplicatas. São definidos por chaves `{ }` e os elementos separados por vírgulas.

In [ ]:
{3,2,5,6,7,1,2,2,3,4}



---
**Exemplo:** Encontre os elementos únicos em uma lista, um tuple e um string usando a função `set()`.


---




In [ ]:
set_1 = set([1,2,2,3,2,1,2])
set_1

In [ ]:
set_2 = set((2,4,6,5,2))
set_2

In [ ]:
set_3 = set("Banana")
set_3

### 2.5 Dicionários `{key:value}`

Dicionários são definidos por chaves `{ }` e os elementos separados por vírgulas, mas cada elemento é um par `chave:valor`. Ao invés de utilizar uma sequência de números para indexar os elementos (i.e., strings, listas e tuples) os dicionários usam "palavras". As chaves podem ser strings, números, ou até tuples (mas não listas).

In [ ]:
dict_1 = {"metano":16.04, "etano":30.07, "propano":44.097}
dict_1



---
**Exemplo:** Obter o elemento "etano" do dicionário `dict_1`.


---




In [ ]:
dict_1["etano"]



---
**Exemplo:** Obter todas as chaves e valores do `dict_1`.


---




In [ ]:
dict_1.keys()

In [ ]:
dict_1.values()



---
**Exemplo:** Definir um dicionário vazio `IUPAC` e adicionar compostos.


---




In [ ]:
IUPAC = {}
IUPAC["metanol"]= 32.04
IUPAC

In [ ]:
IUPAC["etanol"]=46.08
IUPAC

###2.6 Numpy Arrays `np.array`

Numpy é um dos módulos mais fundamentais em Python para a utilização de métodos numéricos e será muito utilizado em nosso curso. Ele é usado para a definição de arranjos (*arrays*) e matrizes $N$-dimensionais (vetores, matrizes e tensores). O modo convencional de importar o módulo `numpy` é usando `np` como abreviação.

In [ ]:
import numpy as np



---
**Exemplo:** Crie o vetor $x=\begin{pmatrix} 1 & 2 & 3\end{pmatrix}$ e a matriz $y = \begin{pmatrix} 1 & 4 & 3 \\ 9 & 2 & 7 \\ 2 & 5 & 6\end{pmatrix}$.


---




In [ ]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
y = np.array([[1,4,3],[9,2,7],[2,5,6]])
y

array([[1, 4, 3],
       [9, 2, 7],
       [2, 5, 6]])



---
**Exemplo:** Determine o número de linhas, colunas e elementos da matriz $y$.


---




In [ ]:
y.shape   # shape é um atributo do objeto y

(3, 3)

In [ ]:
y.size

9



---
**Exemplo:** Crie um array $z$ com elementos de $1$ a $100$ e incrementos de $1$ unidade.


---




In [ ]:
z = np.arange(1,100)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])



---
**Exemplo:** Crie um array $x$ com elementos de $1.0$ a $3.0$ e incrementos de $0.2$.


---




In [ ]:
x = np.arange(1.0,3.0,0.2)
x

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])



---
**Exemplo:** Crie um array $A$ com elementos de $2$ a $15$ e total de $5$ pontos igualmente espaçados.


---




In [ ]:
A = np.linspace(2,15,5)
A

array([ 2.  ,  5.25,  8.5 , 11.75, 15.  ])



---
**Exemplo:** Crie um array $3 \times 4$ com todos os elementos iguais a $0$.


---




In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])



---
**Exemplo:** Crie um array $4 \times 3$ com todos os elementos iguais a $1$.


---




In [ ]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])



---
**Exemplo:** Criar uma matriz zero $2 \times 2$ e preencher os valores $b =
 \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ usando os índices do array.



---




In [ ]:
b = np.zeros((2,2))
b[0,0]=1             # b[linha, coluna]
b[0,1]=2
b[1,0]=3
b[1,1]=4
b

array([[1., 2.],
       [3., 4.]])



---
**Exemplo:** Adicionar e subtrair $2$ à matriz $b =
 \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$. Multiplicar a dividir $b$ por $2$. Elevar cada elemento de $b$ ao quadrado.



---




In [ ]:
b+2

array([[3., 4.],
       [5., 6.]])

In [ ]:
b-2

array([[-1.,  0.],
       [ 1.,  2.]])

In [ ]:
2 * b

array([[2., 4.],
       [6., 8.]])

In [ ]:
b / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [ ]:
b**2

array([[ 1.,  4.],
       [ 9., 16.]])



---
**Exemplo:** Seja $b = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ e $d = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}$. Calcule a soma, subtração, multiplicação, divisão e potenciação dessas matrizes.





---




In [ ]:
b = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])

In [ ]:
b + d

array([[ 6,  8],
       [10, 12]])

In [ ]:
b - d

array([[-4, -4],
       [-4, -4]])

In [ ]:
b*d

array([[ 5, 12],
       [21, 32]])

In [ ]:
b/d

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
b**d

array([[    1,    64],
       [ 2187, 65536]])



---
**Exemplo:** Calcule a raiz quadrada e o seno de cada elemento do vetor $x=[1,4,9,16]$.





---




In [ ]:
x = np.array([1,4,9,16])
np.sqrt(x)

array([1., 2., 3., 4.])

In [ ]:
np.sin(x)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332])

## 3. Funções

### 3.1 Embutidas (*Built-In*)



---
**Exemplo:** Verificar que a fução `len` é uma função embutida.


---




In [ ]:
type(len)

builtin_function_or_method



---
**Exemplo:** Verificar que `np.linspace` é uma função e usar um ponto de interrogação para obter ajuda sobre como usá-la.


---




In [ ]:
import numpy as np
type(np.linspace)

function

In [ ]:
np.linspace?

### 3.2 Definidas `def`

Também é possível definir sua própria função através da palavra-chave `def`.

```python
def nome_da_funcao(parametro_1, parametro_2,...):  # Cabeçalho
    """
    Descrição da Função (opcional)
    Autor, Data  (opcional)
    """
    # Comentários sobre a função
    proposicoes_da_funcao
    
    return parametros_saida (opcional)   # Qualquer tipo de dado (até funções!)
```




---
**Exemplo:** Defina uma função que recebe $3$ números e retorna o produto deles.


---




In [ ]:
def meu_multiplicador(a,b,c):
    """
    Função que multiplica 3 números.
    In: 3 números a,b,c
    Out: produto de a,b,c
    Autor: Pedro Constantino
    Data: 6/10/23
    """
    # Este é o produto
    out = a*b*c

    return out

In [ ]:
help(meu_multiplicador)

Help on function meu_multiplicador in module __main__:

meu_multiplicador(a, b, c)
    Função que multiplica 3 números.
    In: 3 números a,b,c
    Out: produto de a,b,c
    Autor: Pedro Constantino
    Data: 6/10/23



In [ ]:
meu_multiplicador(1,2,3)

6

In [ ]:
meu_multiplicador("Amo","Python",3)

TypeError: ignored

In [ ]:
meu_multiplicador(2,np.pi,np.sin(np.pi/2))

6.283185307179586

In [ ]:
meu_multiplicador(1+2,3*4,5/6)

30.0



---
**Exemplo:** Implementar função com mais de uma saída.


---




In [ ]:
def soma_trigonometrica(a,b):
    """
    Função para demonstrar múltiplas saídas
    sen(a+b) = sen(a)cos(b)+sen(b)cos(a)
    """
    # Relações Matemáticas
    out1 = np.sin(a)+np.cos(b)
    out2 = np.sin(b)+np.cos(a)

    return out1, out2, [out1,out2]

In [ ]:
c,d,e = soma_trigonometrica(2,3)

# Utilizar uma f-string (string formatada)
print(f"c={c}, d={d}, e={e}")

c=-0.0806950697747637, d=-0.2750268284872752, e=[-0.0806950697747637, -0.2750268284872752]




---
**Exemplo:** Implementar função com argumentos padrões.


---




In [ ]:
def email_aluno(nome="Fulereno", dia="segunda"):
    print(f"Olá,  {nome}! Sim, podemos marcar reunião na {dia}")

In [ ]:
email_aluno()

Olá,  Fulereno! Sim, podemos marcar reunião na segunda


In [ ]:
email_aluno(nome="Ciclohexano", dia="quarta")

Olá,  Ciclohexano! Sim, podemos marcar reunião na quarta


### 3.3 Lambda `lambda`

Um atalho mais rápido para definir uma função de uma única linha.

```python
lambda argumentos: expressão
```



---
**Exemplo:** Definir uma função que calcula o quadrado do input.


---




In [ ]:
quad = lambda x: x**2

print(quad(2))
print(quad(5))

In [ ]:
def quad_2(x):
    out = x**2
    return out

quad_2(2)



---
**Exemplo:** Definir uma função que soma $ x$ e $ y$


---




In [ ]:
soma = lambda x,y: x+y
soma(2,4)

## 4. Local vs Global

Uma função tem o seu próprio bloco de memória exclusivo para as variáveis criadas dentro da função. Essa memória não é compartilhada com o resto do Jupyter Notebook ou o programa principal.

### 4.1 Variáveis Locais e Globais



---
**Exemplo:** Usar uma variável `out` dentro de uma função e outra variável com o mesmo nome fora da função.


---




In [ ]:
def meu_multiplicador(a,b,c):
    out = a*b*c
    print(f"O valor de out dentro da função é {out}")
    return out

out = 10
d = meu_multiplicador(1,2,3)
print(f"O valor de out fora da função é {out}")

O valor de out dentro da função é 6
O valor de out fora da função é 10




---
**Exemplo:** Defina uma variável $n$ fora de uma função e tente usar dentro da função. Depois tente mudar essa variável dentro da função.


---




In [ ]:
n = 31

def func():
    print(f"Dentro da função o valor de n é {n}")
    n = 13
    print(f"Dentro da função: mudei n para {n}")
    return

func()
print(f"Fora da função o valor de n é {n}")

UnboundLocalError: ignored

In [ ]:
n = 31

def func():
    #print(f"Dentro da função o valor de n é {n}")
    n = 13
    print(f"Dentro da função: mudei n para {n}")
    return

func()
print(f"Fora da função o valor de n é {n}")

Dentro da função: mudei n para 13
Fora da função o valor de n é 31


In [ ]:
n = 31

def func():
    global n     # Agora n é uma variável global!
    print(f"Dentro da função o valor de n é {n}")
    n = 13
    print(f"Dentro da função: mudei n para {n}")
    return

func()
print(f"Fora da função o valor de n é {n}")

Dentro da função o valor de n é 31
Dentro da função: mudei n para 13
Fora da função o valor de n é 13


### 4.2 Funções Aninhadas (*Nested*)



---
**Exemplo:** Calcule todas as distâncias entre 3 pontos $x=(0,0), y=(0,1), z=(1,1)$


---




In [ ]:
import numpy as np

def dist_xyz(x,y,z):
    """
    in: x, y, z são coordenadas 2D (tuples)
    out: d - lista, onde:
         d[0] é a distância entre x e y
         d[1] é a distância entre x e z
         d[2] é a distância entre y e z
    """
    def dist(x,y):
        out = np.sqrt((x[0]-y[0])**2+(x[1]-y[1])**2)
        return out

    d0=dist(x,y)
    d1=dist(x,z)
    d2=dist(y,z)

    return [d0,d1,d2]

In [ ]:
d = dist_xyz((0,0),(0,1),(1,1))
print(d)

[1.0, 1.4142135623730951, 1.0]


In [ ]:
d = dist((0,0),(0,1))   #A função interna (filha) não é "vista" fora da função externa (mãe)

NameError: ignored

In [ ]:
import numpy as np

def dist_xyz(x,y,z):
    """
    in: x, y, z são coordenadas 2D (tuples)
    out: d - lista, onde:
         d[0] é a distância entre x e y
         d[1] é a distância entre x e z
         d[2] é a distância entre y e z
    """

    d0=np.sqrt((x[0]-y[0])**2+(x[1]-y[1])**2)
    d1=np.sqrt((x[0]-z[0])**2+(x[1]-z[1])**2)
    d2=np.sqrt((y[0]-z[0])**2+(y[1]-z[1])**2)

    d = [d0,d1,d2]

    return d

In [ ]:
d = dist_xyz((0,0),(0,1),(1,1))
print(d)

[1.0, 1.4142135623730951, 1.0]


In [ ]:
range(1,5)[:]

range(1, 5)